# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

env:
  CONFIG: ${{  secrets.CONFIG }}
  RULES: ${{  secrets.RULES }}

on:
  workflow_dispatch:

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: set files
      run: |
        cat >> ./config.gsil.cfg <<EOF
        ${{ env.CONFIG }}
        EOF
        cat >> ./rules.gsil.yaml <<EOF
        ${{ env.RULES }}
        EOF
    - name: run python
      run: |
        python3 gsil.py ohdat
